// stdlib
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>
#include <assert.h>
#include <vector>
#include <poll.h>
#include <fcntl.h>

// Socket state
struct Conn {
  int fd = -1;
  bool want_read = false;
  bool want_write = false;
  bool want_close = false;
  // buffered input and output
  std::vector<uint8_t> incoming;  // data to be parsed by the application
  std::vector<uint8_t> outgoing;  // responses generated by the application
};


static void msg(const char *msg) {
  fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
  fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
  int err = errno;
  fprintf(stderr, "[%d] %s\n", err, msg);
  abort();
}

static void fd_set_nb(int fd) {
  errno = 0;
  int flags = fcntl(fd, F_GETFL, 0);
  if (errno) {
    die("fcntl error");
    return;
  }

  flags |= O_NONBLOCK;

  errno = 0;
  (void)fcntl(fd, F_SETFL, flags);
  if (errno) {
    die("fntl error");
  }
}

static int32_t read_full(int connfd, char *rbuf, size_t n) {
  // read expected number of bytes into rbuf
  while (n > 0) {
    ssize_t read_bytes = read(connfd, rbuf, n);
    if (read_bytes <= 0) {
      return -1; // Early EOF or error
    }
    // decrement bytes to read
    assert((size_t)read_bytes <= n);
    n -= (size_t)read_bytes;
    rbuf += read_bytes;
  }
  return 0;
}

static int32_t write_all(int connfd, const char *wbuf, size_t n) {
  while (n > 0) {
    ssize_t write_bytes = write(connfd, wbuf, n);
    if (write_bytes <= 0) {
      return -1;  // write error
    }
    // decrement bytes to write
    assert((size_t)write_bytes <= n);
    n -= write_bytes;
    wbuf += write_bytes;
  }
  return 0;
}

static Conn* handle_accept(int server_fd) {
  struct sockaddr_in client_addr = {};
  socklen_t addrlen = sizeof(client_addr);
  int connfd = accept(server_fd, (struct sockaddr *)&client_addr, &addrlen);
  if (connfd < 0) {
    msg_errno("accept() error");
    return NULL;
  }

  uint32_t ip = client_addr.sin_addr.s_addr;
  fprintf(stderr, "new client from %u.%u.%u.%u:%u\n",
    ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24,
    ntohs(client_addr.sin_port)
  );

  // set new connection fd to nonblocking mode
  fd_set_nb(connfd);

  // create a 'struct Conn' allocated in heap
  Conn *conn = new Conn();
  conn->fd = connfd;
  conn->want_read = true;
  return conn;
}

const size_t k_max_msg = 4096;

static int32_t handle_response(int connfd, void *rbuf, uint32_t msg_len) {
  char wbuf[4 + k_max_msg];
  memcpy(wbuf, rbuf, 4 + msg_len);
  int32_t err = write_all(connfd, wbuf, msg_len);
  if (err) {
    msg("Error writing response");
    return -1;
  }
  return 0;
} 

// handle_request will call full_read() twice -- once to get msg len, then to get msg body
static int32_t one_request(int connfd) {
  char rbuf[4 + k_max_msg];
  errno = 0;
  // Read msg len to first 4 bytes of rbuf
  int32_t err = read_full(connfd, rbuf, 4);
  if (err) {
    msg(errno == 0 ? "EOF" : "read() error");
    return err;  // full_read error
  }

  // Get total msg len from first 4 bytes read
  uint32_t msg_len = 0;
  memcpy(&msg_len, rbuf, 4);
  fprintf(stdout, "%llu\n", (unsigned long long)msg_len);

  if (msg_len > k_max_msg) {
    fprintf(stdout, "%llu\n", (unsigned long long)msg_len);
    msg("Message body too long");
    return -1;
  }

  // Read msg body to rbuf
  err = read_full(connfd, &rbuf[4], msg_len);
  if (err) {
    return -1;  // full_read error
  }
  
  err = handle_response(connfd, &rbuf[4], msg_len);

  return 0;
}

static void handle_read(Conn *conn) {

}

static void handle_write(Conn *conn) {

}

int main() {
  // Start listening socket
  int server_fd = socket(AF_INET, SOCK_STREAM, 0);
  if (server_fd < 0) {
    die("socket()");
  }

  int val = 1;
  setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &val, sizeof(val));
  
  // Bind
  struct sockaddr_in addr = {};
  addr.sin_family = AF_INET;
  addr.sin_port = htons(1234);  // port
  addr.sin_addr.s_addr = htonl(0);  // wildcard IP 0.0.0.0
  int rv = bind(server_fd, (const struct sockaddr *)&addr, sizeof(addr));
  if (rv) {
    die("bind()");
  }

  // Listen
  rv = listen(server_fd, SOMAXCONN);
  if (rv) {
    die("listen()");
  }

  // vector of client conn states, keyed by fd
  std::vector<Conn *> fd2conn;
  // event loop
  std::vector<struct pollfd> poll_args;

  while (true) {
    // Clear old pollfds
    poll_args.clear();
    // Set listening socket to first position
    struct pollfd pfd = {server_fd, POLLIN, 0};
    poll_args.push_back(pfd);

    // Iterate thru existing conns and create new pollfd objects
    for (Conn *conn : fd2conn) {
      if (!conn) {
        continue;
      }
      struct pollfd pfd = {conn->fd, POLLERR, 0};
      if (conn->want_read) {
        pfd.events |= POLLIN;
      }
      if (conn->want_write) {
        pfd.events |= POLLOUT;
      }
      poll_args.push_back(pfd);
    }

    // Wait for readiness
    int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
    if (rv < 0 && errno == EINTR) {
      continue; // not an error
    }
    if (rv < 0) {
      die("poll()");
    }

    // handle listening socket
    if (poll_args[0].revents) {
      Conn *conn = handle_accept(server_fd);
      if (conn) {
        if (fd2conn.size() <= (size_t)conn->fd) {
          fd2conn.resize(conn->fd+1);
        }
        assert(!fd2conn[conn->fd]);
        fd2conn[conn->fd] = conn;
      }
    }

    // handle ready connection sockets
    for (size_t i = 1; i < poll_args.size(); ++i) {
      uint32_t ready = poll_args[i].revents;
      if (ready == 0) {
        continue; // not ready
      }

      Conn *conn = fd2conn[poll_args[i].fd];
      if (ready & POLLIN) {
        assert(conn->want_read == true);
        handle_read(conn); // application logic
      }
      if (ready & POLLOUT) {
        assert(conn->want_write == true);
        handle_write(conn); // application logic
      }
      if (ready & POLLERR || conn->want_close) {
        (void)close(conn->fd);
        fd2conn[conn->fd] = NULL;
        delete conn;
      }
    }

    

    while (true) {
      uint32_t err = one_request(connfd);
      if (err) {
        break;
      }
    }

    close(connfd);
  }
  return 0;
}